### ISSUE TITLE
unable to load file

### ISSUE THREAD

**Issue by My-selforever** [sglkc/moegi#12]
The following error : 
Manifest file is missing or unreadable
Could not load manifest.

I have done the following:
Download zip file of code
Extract all
Toggle dev mode
Click on load unpacked
Click on extracted file

**Comment by sglkc** [comment]
![image](https://github.com/user-attachments/assets/aaa238a0-2de0-45a4-b5cd-bd2ee5768d4f)

you clicked on the wrong folder

**Comment by My-selforever** [comment]
I've tried that too, and i did it again today, same error
