### ISSUE TITLE
question,

### ISSUE THREAD

**Issue by Hubert1999** [sglkc/moegi#15]
Is it possible to make this extension work with spicify ?
I ask because there are some songs that don't have lyrics working on spotify but work on spicify
Or maybe is it possible if the extension could fetch lyrics from the musixmatch server as that is the most complete one?

**Comment by sglkc** [comment]
This extension is inspired from Spicetify so if you have it then you don't really need this. Musixmatch API requires a token and I don't want that

https://github.com/spicetify/cli/blob/main/CustomApps/lyrics-plus/README.md

**Comment by Hubert1999** [comment]
Yeah but spicify doesn't have translations only romaji for
chinese/kor/Japan 🫢

**Comment by sglkc** [comment]
you can ask them for the feature instead

**Comment by Hubert1999** [comment]
OK thanks
