### ISSUE TITLE
The translation does not work for me

### ISSUE THREAD

**Issue by bunnicio** [sglkc/moegi#3]
[open.spotify.com-1704527945406.log](https://github.com/sglkc/moegi/files/13848783/open.spotify.com-1704527945406.log)

maybe it's some mistake of mine

**Comment by sglkc** [comment]
Thanks for the report! I haven't updated the extension for months and I think there are breaking changes on Spotify side. I'll fix this issue, so keep eyes on this thread until then

**Comment by sglkc** [comment]
I have released a new version, please kindly try it out and see if there are any issues, thanks!

https://github.com/sglkc/moegi/releases/tag/1.0.2

**Comment by bunnicio** [comment]
Fully functional, thank you very much.
