### ISSUE TITLE
Chinese and Cyrylic Romaji Please <3

### ISSUE THREAD

**Issue by Hubert1999** [sglkc/moegi#5]
Kashi Extension has this feature for Cyrylic/China/KOR/JAP
https://github.com/Cristian-Sknz/kashi-extension
maybe use the same romaji translation for Cyrylic/China.

Then we could expand it to other non latin languages.
https://www.lexilogos.com/keyboard/index.htm

**Comment by sglkc** [comment]
Thanks for using Moegi and for your suggestion! I see that kashi extension no longer get support for a couple years, so I will work on expanding the romanization.

I'll notify you once it's ready 👍

**Comment by Hubert1999** [comment]
I found another extension
Maybe you can use the same thing used to get romaji for Chinese and cyrylic as this one

https://github.com/JoshLmao/Genify

**Comment by Hubert1999** [comment]
in the kashi extension there a problem russian small p should be r in latin but it doesn't change.

![image](https://github.com/sglkc/moegi/assets/48352603/dcbeab7f-bf06-4bac-aad2-305a2f0e754b)

**Comment by Hubert1999** [comment]
Ah yes I see now.
Thank you for explaining

**Comment by sglkc** [comment]
There is a way to turn on romanization in Spotify mobile app, but none on the desktop version. It's the only reason why I made this extension.

I have released a new version, check it out https://github.com/sglkc/moegi/releases/tag/1.2.0

**Comment by Hubert1999** [comment]
Thank you very much.
How can you turn on romaji on the app??!!??

I use musixmatch app and genius for cyrylic romaji on android. 
On my android tablet I use kiwi browser and romaji extension which runs just like on pc.

**Comment by Hubert1999** [comment]
do you think its possible to expand this extension to romaji greek or thai too ? :)

**Comment by sglkc** [comment]
> Thank you very much for the update :)
> 
> How can you turn on romaji on the spotify mobile app??!!??
> 
> I use musixmatch app for JAP/KOR/China and genius for cyrylic romaji on android. On my android tablet I use kiwi browser and romaji extension which runs just like on pc.

Nevermind, it was for translation and not romaji xD

> do you think its possible to expand this extension to romaji greek or thai too ? :)

It's never impossible 💯

**Comment by Hubert1999** [comment]
also maybe for translation add an option to choose colour of text :)

Greek
Thai
Lao, Burmese , Ethiopian Amharic would be a challenge

**Comment by sglkc** [comment]
> also maybe for translation add an option to choose colour of text :)
> 
> Greek Thai Nepal, India, Sri Lanka (I think musixmatch supports) Lao, Burmese , Ethiopian Amharic would be a challenge

There are already color options in lyric styling.

Most of them are challenges because I depend on available packages, if there's none then I can't add it ¯⁠\⁠_⁠(⁠ツ⁠)⁠_⁠/⁠¯

**Comment by Hubert1999** [comment]
you can change size of translated text but not the colour 
be good to differentiate it from the normal lyrics.
yeah challenges with packages for sure. 
But you have created a masterpiece so far with this extension :)

It bogles the mind how a multi million corp haven't added romaji yet officially..
people have constantly been asking for it on spotify forums and reddit for years now.

**Comment by Hubert1999** [comment]
I found this for hindi languages

https://www.npmjs.com/package/kvz-transliteration


hebrew
https://www.npmjs.com/package/hebrew-transliteration

greek

https://www.npmjs.com/package/greek-conversion

arabic

https://www.npmjs.com/package/arabize

georgian

https://www.npmjs.com/package/translitit-latin-to-mkhedruli-georgian

**Comment by sglkc** [comment]
Thanks for the help, sorry I had to pause development. I just realized its easier, faster, and smaller to just use an ASCII converter, it also works for any script despite not having any options :facepalm:

**Comment by Hubert1999** [comment]
That's great so converting any language/script is possible

**Comment by sglkc** [comment]
You may check the new version here https://github.com/sglkc/moegi/releases/tag/1.2.1

**Comment by Hubert1999** [comment]
testing :)
It works great for Greek, Armenia, Georgia
Semi for Ethiopia/Thai
A bit broken for Burma

**Comment by Hubert1999** [comment]
arabic example

![image](https://github.com/sglkc/moegi/assets/48352603/1928212f-cdc8-42f5-aa4a-a79d84580ccf)
is vs should
![image](https://github.com/sglkc/moegi/assets/48352603/b5cec5d8-541b-4b4e-936b-af0bd37a351f)



https://lyricstranslate.com/en/Nancy-Ajram-Ya-Tabtab-wa-dala3-lyrics.html

**Comment by sglkc** [comment]
It's expected for Arabic script to be like that, most of them are written without any vowel marks/diacritics so it's impossible to know the pronunciation without any knowledge. I don't know about the others though.

**Comment by Hubert1999** [comment]
Is there any converter for Arabic to latin?
Maybe using this one? 
https://www.npmjs.com/package/arabize

**Comment by Hubert1999** [comment]
same problem with hebrew

![image](https://github.com/sglkc/moegi/assets/48352603/849bfaad-a40e-4041-bac6-039122f73465)

![image](https://github.com/sglkc/moegi/assets/48352603/82b42f0d-f6ef-4457-ae84-84f5c950eefd)

maybe use this one

https://www.npmjs.com/package/hebrew-transliteration

**Comment by Hubert1999** [comment]
ethiopia

![image](https://github.com/sglkc/moegi/assets/48352603/7c353a72-e611-4e66-86cd-3f10b4f5fa64)

![image](https://github.com/sglkc/moegi/assets/48352603/a8a3a97a-4865-4d73-9931-8a3255503c18)

**Comment by Hubert1999** [comment]
georgian 100%

![image](https://github.com/sglkc/moegi/assets/48352603/5aaa3213-e285-4981-8faa-b2ec8b0f1ab2)

![image](https://github.com/sglkc/moegi/assets/48352603/3351c9c3-ba3b-4040-ae2d-1b1e7a2cbcac)

**Comment by Hubert1999** [comment]
armenia

![image](https://github.com/sglkc/moegi/assets/48352603/322b598e-b28d-4649-950a-413e7417b841)

![image](https://github.com/sglkc/moegi/assets/48352603/24a1a075-d130-4c86-9310-3a804c78c716)

**Comment by Hubert1999** [comment]
nepal 80%

![image](https://github.com/sglkc/moegi/assets/48352603/8049f05b-cbaf-4728-a2af-848110cbcf09)

![image](https://github.com/sglkc/moegi/assets/48352603/0c079429-06ca-45a9-86c5-83ed290d40ed)

**Comment by sglkc** [comment]
> Maybe use this one for arabic https://www.npmjs.com/package/arabize

That's for latin to arabic, not the other way around. For your information, this is an example of an arabic sentence with vowels

![image](https://github.com/sglkc/moegi/assets/31957516/0fd9ad50-a493-4071-b9d9-7994b2ad2ba7)

> same problem with hebrew
> 
> maybe use this one
> https://www.npmjs.com/package/hebrew-transliteration

The same issue like arabic, it doesn't have any vowel diacritics like this

![image](https://github.com/sglkc/moegi/assets/31957516/0495765b-bb21-4bb5-a161-27f71cf79114)

**Comment by Hubert1999** [comment]
ah
maybe this one?

https://github.com/bashartalafha/Arabizi-Transliteration

**Comment by Hubert1999** [comment]
hebrew
https://github.com/charlesLoder/hebrew-transliteration

for many scripts
https://github.com/twardoch/gimeltra

**Comment by sglkc** [comment]
> ah maybe this one?
> 
> https://github.com/bashartalafha/Arabizi-Transliteration

> hebrew https://github.com/charlesLoder/hebrew-transliteration
> 
> for many scripts https://github.com/twardoch/gimeltra

What I'm saying is, whatever the library, it's simply impossible to get the vowels if the lyrics itself doesn't contain any vowels, also 2 of the repositories you've sent is for Python.

I'm just a developer for the extension, not a programming nor a language expert, so if you still persist on getting it working then I can't help.

**Comment by Hubert1999** [comment]
I understand.
Thanks for all your work with this extension :)
