### ISSUE TITLE
Extension stopped working (got some errors while using the extension)

### ISSUE THREAD

**Issue by Hubert1999** [sglkc/moegi#8]
![image](https://github.com/user-attachments/assets/99e58b37-09cc-4d6a-980c-c8b2065c3c5b)

**Comment by Hubert1999** [comment]
its a problem only on chrome 

(loaded extension on edge and it works perfectly)

![image](https://github.com/user-attachments/assets/3fc5e6a6-b857-4b73-93e2-294322b85830)

**Comment by sglkc** [comment]
Fixed https://github.com/sglkc/moegi/releases/tag/1.2.2 it was a dependency issue
